### ISSUE TITLE
Frontend is unable to send HTTP requests to the Backend

### ISSUE THREAD

**Issue by Tech-Gunner** [Tech-Gunner/TechGunner#1]
**Describe the bug**
Frontend is unable to fetch data from the Backend, Even when the port is exposed.

**To Reproduce**
1. Run docker compose up
1. Go to http://localhost:5173/profile/@techgunner
4. Check the terminal console to see the error

**Error message**
cause: ConnectionRefused: Unable to connect. Is the computer able to access the url?
path: "http://localhost:3000/profile/@techgunner"

**Comment by yassinebkr** [comment]
It seems like your frontend is unable to connect to your backend. This could be due to several reasons. Here are some suggestions to troubleshoot this issue:

1. Make sure your backend is running and listening on the correct port. You can check this by directly accessing your backend's URL in your browser or using a tool like curl or Postman.

2. Check that your backend is configured to accept connections from your frontend. If your backend uses a CORS (Cross-Origin Resource Sharing) policy, make sure it's set up to accept requests from your frontend.

3. If you're using Docker, ensure your Docker services are set up to communicate with each other. This might involve making sure both services are on the same Docker network, or that the appropriate ports are exposed and mapped correctly.

4. Verify that your backend's URL is correct. In your error message, the URL is "http://localhost:3000/profile/@techgunner". Make sure this URL is correct and that your backend is set up to respond to this route.

5. Lastly, check that your frontend is correctly making the request to your backend. This could involve checking your frontend's code to ensure it's using the right URL and port, and that it's making the request correctly.

If you continue to encounter issues, I recommend providing more details about your setup, including your frontend and backend code, as well as your docker-compose file, so I can assist you further.

this is what copilot said

**Comment by Tech-Gunner** [comment]
@yassinebkr Please try to fork the repo and help me debug this issue, if you solve this issue I'll merge your pull request

**Comment by Tech-Gunner** [comment]
@psibean solved the issue
